### ISSUE TITLE
Base Library somehow messes up font rendering

### ISSUE THREAD

**Issue by Revemohl** [Eternal-Team/BaseLibrary#1]
Strange issue, I even made a fresh instance to test it.

No mods:
![1](https://i.imgur.com/0A4VZ4U.png)
After downloading and enabling Base Library:
![2](https://i.imgur.com/dNH5wX7.png)

You can see that the font spacing is somehow wider after enabling the mod, for some reason.

**Comment by Itorius** [comment]
Fixed
