### ISSUE TITLE
Mousposition does not match cursor

### ISSUE THREAD

**Issue by simonfruehauf** [Eternal-Team/BaseLibrary#2]
The mouse cursor cannot reach the edges of the game, and hovering (and clicking on) buttons clicks somewhere else (closer to the center of the screen).

**Comment by simonfruehauf** [comment]
![baselibrary bug](https://user-images.githubusercontent.com/25452923/82672573-cf6ba600-9c40-11ea-9034-b8a8472852d1.gif)

**Comment by thehemmo** [comment]
I have same problem. solved after deleting base lib. its visible when frame skip is off.
![kuva](https://user-images.githubusercontent.com/46715657/83335845-2f54f300-a2b8-11ea-808a-60c93a8db77a.png)

**Comment by nuxonom** [comment]
Having same issue here.
With the mod enabled, cursor can't move below the bottom 20ish% of the screen. Even with fullscreen (not borderless), the mouse can escape the game window. The difference between mouse and cursor position increases the further away from screen center the mouse is. It is possible to activate all UI elements.
From what I've seen so far, the game seems to read from cursor position in the main (read: white text only menus) and mouse position in the other (read: blue window menus), handily shown in OP's gif. The exception to the white text menu part is during player/map name and seed value entry.
I did a small bit of testing in a loaded map and didn't see any mouse/cursor difference.

Base Library 1.3.2
tModLoader 0.11.7.5

**Comment by Itorius** [comment]
I've been working this issue with Ralgor but we still don't know what is causing it.

**Comment by Itorius** [comment]
Base Library v1.3.3 fixes the "unable to move the mouse beyond some point" bug.
