### ISSUE TITLE
Keypress issue with Magic Storage mod and others.

### ISSUE THREAD

**Issue by F0x06** [Eternal-Team/BaseLibrary#3]
Hi, i just copy-paste the well-explained message of `Zauberin Paracelsus` from Terraria Forums

```
The Base Library mod is creating an issue with the Magic Storage mod. When Base Library is installed, any time I open Magic Storage's interface and click into the Search Name or Search Mod field, it immediately enters in a bunch of text from previous keypresses, usually spaces and the WASD keys.

EDIT: Disabling the Base Library mod has also fixed a couple of other UI-related bugs I had been experiencing:
1. The Wing Slot mod is rendered mostly non-functional with the Base Library mod installed.
2. You cannot scroll through the chat history in the chat interface.
```

Also, the keypress issue can be simply triggered from the main menu, if you press enter on the main menu you can hear the chat opening sound.

Thanks.

**Comment by F0x06** [comment]
Apparently the same issues occurs with Search TextInput field of Cheat Sheet mod, it's like other mods are catching all key events when BaseLibrary is installed

**Comment by zauberparacelsus** [comment]
I just installed yesterday's update to Base Library, and all of the reported issues are still present.

There is also a fourth issue I've observed: the effects of the Alchemy Table are being applied to *all* items crafted, regardless of where you craft them.

**Comment by Axepoi** [comment]
All of the previous issues are still there. 
And another chat related issue is that the text box where you write doesn't appear and also makes it so that commands don't work.

**Comment by Itorius** [comment]
Closing, not relevant to tML 1.4.
